package dev.olliesbrother.skill.events;

import dev.olliesbrother.config.ConfigManager;
import dev.olliesbrother.experience.sources.MiningExperienceSource;
import dev.olliesbrother.persistence.SkillforgeState;
import dev.olliesbrother.skill.ExperienceManager;
import dev.olliesbrother.skill.Skill;
import dev.olliesbrother.skill.SkillRegistry;
import dev.olliesbrother.skill.abilities.passive.ProspectorPassive;
import dev.olliesbrother.skill.abilities.active.SuperBreakerAbility;
import net.fabricmc.fabric.api.event.player.PlayerBlockBreakEvents;
import net.minecraft.item.ItemStack;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.server.world.ServerWorld;
import net.minecraft.util.Identifier;

public final class MiningEvents {

    private static final Identifier MINING_ID =
            Identifier.of("skillforge", "mining");

    private MiningEvents() {
    }

    public static void register() {

        PlayerBlockBreakEvents.AFTER.register(
                (world, player, pos, state, blockEntity) -> {

                    if (!(world instanceof ServerWorld serverWorld)) {
                        return;
                    }

                    if (!(player instanceof ServerPlayerEntity serverPlayer)) {
                        return;
                    }

                    /*
                     * Always remove the player-placed marker when
                     * its block gets broken.
                     */
                    boolean playerPlaced =
                            SkillforgeState
                                    .get(serverWorld.getServer())
                                    .isPlayerPlaced(
                                            serverWorld,
                                            pos
                                    );

                    if (serverPlayer.isCreative()) {
                        return;
                    }

                    if (!ConfigManager.get().mining.enabled) {
                        return;
                    }

                    ItemStack tool =
                            serverPlayer.getMainHandStack();

                    boolean correctTool =
                            tool.isSuitableFor(state);

                    /*
                     * Normal Mining XP can optionally require the
                     * correct tool.
                     */
                    if (ConfigManager.get()
                            .mining
                            .requireCorrectTool
                            && !correctTool) {

                        return;
                    }

                    /*
                     * SUPER BREAKER
                     *
                     * Only the block manually broken by the player
                     * should create the 3x3.
                     *
                     * Extra blocks generated by Super Breaker still
                     * come through this MiningEvents callback, but
                     * PROCESSING prevents recursive 3x3 breaking.
                     */
                    if (correctTool
                            && SuperBreakerAbility.isActive(serverPlayer)
                            && !SuperBreakerAbility.isProcessing(serverPlayer)) {

                        SuperBreakerAbility.breakArea(
                                serverWorld,
                                serverPlayer,
                                pos
                        );
                    }

                    /*
                     * Player-placed blocks may still be physically
                     * broken by Super Breaker, but they never give
                     * Mining XP or trigger Prospector.
                     */
                    if (playerPlaced) {
                        return;
                    }

                    double experience =
                            MiningExperienceSource.INSTANCE
                                    .getExperience(state);

                    if (experience <= 0) {
                        return;
                    }

                    Skill mining =
                            SkillRegistry.get(MINING_ID);

                    if (mining == null) {
                        return;
                    }

                    ExperienceManager.addExperience(
                            serverPlayer,
                            mining,
                            experience
                    );

                    ProspectorPassive.tryApply(
                            serverWorld,
                            serverPlayer,
                            pos,
                            state,
                            blockEntity
                    );
                }
        );
    }
}